# Generated by Django 4.2.1 on 2023-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcing', models.CharField(max_length=36, verbose_name='аутсорсинг')),
                ('design_one', models.CharField(max_length=36, verbose_name='Разработка дизайна')),
                ('mobileappl_one', models.CharField(max_length=50, verbose_name='Разработка мобильных приложений')),
                ('design_two', models.CharField(max_length=36, verbose_name='Разработка дизайна')),
                ('design_three', models.CharField(max_length=36, verbose_name='Разработка дизайна')),
                ('mobileappl_two', models.CharField(max_length=50, verbose_name='Разработка мобильных приложений')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
            },
        ),
    ]
