# Generated by Django 4.2.1 on 2023-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image/client', verbose_name='Фотография')),
                ('title_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title_en', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Наши клиенты',
                'verbose_name_plural': 'Наши клиенты',
                'db_table': 'customers',
            },
        ),
    ]
