# Generated by Django 4.2.1 on 2023-05-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0005_instruments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/icon', verbose_name=' фотографии')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Технологии и Инструменты',
                'verbose_name_plural': 'Технологии и Инструменты',
                'db_table': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'db_table': 'technologies_category',
            },
        ),
    ]
