# Generated by Django 4.2.1 on 2023-05-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0006_technologies_technologiescategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motion_app.technologiescategory'),
            preserve_default=False,
        ),
    ]
