# Generated by Django 4.2.1 on 2023-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='iphone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_one',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Имя'),
        ),
    ]
